dist: trusty
sudo: required
services:
- docker
language: scala
script:
- sbt "++${TRAVIS_SCALA_VERSION}" test scripted
matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.12.6
env:
  global:
  - secure: rcba+Co7geWSApgaYTffWSLRxPpZIcpvqmE7qStKHLwrD6tUfQKrpymH9/KILJKz6L80YwPvtgWFNxhck7roMxT8V6ySccFuCKIM4S4UGaSEKJc4v/b/d9i+P4qmS320iDi8FEL//TCCpmNttTkYxeKwCr6VYcu1/62BjBTQdDZLD9BmiLhVklPVdlzx2Lk5NQmMdpJO0uzQ1xYAdXHVfq/Zh63vEHy+aw88WpfhO+rTIXE/lzdSSCrUQNEWeM8otdF01xC4byphlN3QBIWhS98YkfUg+rtLqssMM1FGUXxGag4xXvQo/2U7osfwCODJ0d4RvQ4P9U9jMzckprrW6JiC5yGDp+i4cGbz/fLM/3IMXXNdpgh7FWN6eJfxvaLdBdmGJy2SB8bfCVBWmyI1t1udjrGYtOaxo9oXEDFstg4CP/S9q0eLBezAVYJMLjV04ipsw60rxKIGsf0feaAJ/Y4lBeRZ1yC9gYGNv/X2Pr3J0oiaQMnvCpH1eKwz/7YWJ5jS7yUlQ+NILQAEk0ALQehYsYOEk6aQtyiURVWG1qCh4xfJ1Ak4tkXm8Zjj37kB6XpC1c76wlMfv1mRWnYCgjnDoyxI7jZ1Zn62engA4swkzhnDx/scme0Iaxx+4w9brZYU9EwZDuQsnNOW/1C59E9makFf8mCJ8RDh3n/H7rc=
  - secure: QB5wRsabBzOoy9ZVtbiMwc1weBuTLmSgU4VwdCoxQ2FMrJWdlUjhezu8hdnENRqIkL6UGiwlKhYdJF7v3FXmRseRYYJeWcfFIW4blh89E6ZgevPxPT+KURvRS46Irb2IS5Vpby1HTAQJYz8MnwAip57BGbiVYOSQCoHslFTu/w1bQgGHgii0CvDdo2cWlcMG7jT0aFMlQ9tVGremMUDbjIRvqEiPqMJRWGKdm1wCP2jecI9Le79jEB5IH2l92ZRhFelL0xDIGUBUEGiDWgUewomG32kqjP+TODfVvYjFaEXj4jv+MYGxxWUDijdc/SHfixq8j1d5E33QRIGMaPlFIoXu0o5kMxfHkVb5ZNaIS/vbXAKMQZ1dXGbqvZtKm4xBGWH+06D1YjZ0xZ8UXUKHekQnXZuCzXQ9K5EW70sQGamVQJz8JHu5kWbI/tRZ4qwbfKdSAPeZoppG+UuAClPvDMhd82vMSV5OpeS28qF19+J1jfmGahJab+3BGJeVul/nUBoPcAeP/4mdSZWkMNMNG+yJXZSREI9trNN8i9Ot0FfFVBuwHAm9FboR2tDlb4t9j7keQCYe6fVuhnuafmxhE3HunhumCdmJZXQ0PrDNs4ik/9z48KijboT/Cqa0uv2dae6ebwH5e5SfZV8wZLvgEmGYYGWUupwMzQhyPeRR4eU=
